{
 "title": "k6.io metrics with statsd_exporter and Prometheus",
 "description": "k6.io load tests results",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "K6RequestName",
    "label": "K6 Request Name",
    "query": {
     "query": "label_values(k6_http_req_duration_count, name)"
    }
   },
   {
    "name": "GoHttpMetricName",
    "label": "Go HTTP Metric Name",
    "query": "req_duration,req_blocked,req_connecting,req_receiving,req_sending,req_tls_handshaking,req_waiting"
   }
  ]
 },
 "panels": [
  { "title": "Global metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Iterations per second",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(k6_iterations[$__rate_interval]))",
     "legendFormat": "{{scenario}}"
    }
   ]
  },
  {
   "title": "Virtual Users",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "VUs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "k6_vus" }
   ]
  },
  {
   "title": "% Failed Checks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(k6_check{outcome=\"fail\"}[$__rate_interval])) / sum(rate(k6_check[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(k6_data_received[$__rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(rate(k6_data_sent[$__rate_interval]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(k6_script_errors[$__rate_interval]))",
     "legendFormat": "Script errors"
    }
   ]
  },
  {
   "title": "K6 HTTP Request: ${K6RequestName}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "repeat": "K6RequestName"
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(k6_http_reqs{name=\"${K6RequestName}\"}[$__rate_interval]))",
     "legendFormat": "HTTP {{status}}"
    }
   ]
  },
  {
   "title": "Latency (${GoHttpMetricName})",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 10, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(k6_http_${GoHttpMetricName}_bucket{name=\"${K6RequestName}\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Mean latency (${GoHttpMetricName})",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "1000*sum (rate(k6_http_${GoHttpMetricName}_sum{name=\"${K6RequestName}\"}[$__rate_interval]))/sum (rate(k6_http_${GoHttpMetricName}_count{name=\"${K6RequestName}\"}[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "90th percentile latency (${GoHttpMetricName})",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "1000*histogram_quantile(0.90, sum(rate(k6_http_${GoHttpMetricName}_bucket{name=\"${K6RequestName}\"}[$__rate_interval])) by (le))"
    }
   ]
  }
 ]
}