---
- hosts: all
  become: true
  tasks:
    - name: Get Public IP
      shell: dig +short myip.opendns.com @resolver1.opendns.com
      register: public_ip

    - name: Get Droplet ID
      command: curl -s http://169.254.169.254/metadata/v1/id
      register: droplet_id

    - name: Add the user 'kubedev'
      ansible.builtin.user:
        name: kubedev
        home: /home/kubedev/
        shell: /bin/bash
        group: sudo
        password: kubedev

    - name: Add SSH key to 'kubedev'
      authorized_key:
        user: kubedev
        state: present
        key: "{{ lookup('file', pub_key) }}"

    - name: Install packages that allow apt to be used over HTTPS
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common

    - name: Install additional necessary packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - bash-completion
          - mosquitto-clients
          - nfs-kernel-server

    - name: Add an apt signing key for Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add apt repository for stable version
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present

    - name: Install docker and its dependecies
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - docker-ce
          - docker-ce-cli
          - containerd.io
      notify:
        - docker status

    - name: Add kubedev user to docker group
      user:
        name: kubedev
        group: docker

    - name: Remove swapfile from /etc/fstab
      mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      with_items:
        - swap
        - none

    - name: Disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: Add an apt signing key for Kubernetes
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Adding apt repository for Kubernetes
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes.list

    - name: Install Kubernetes binaries
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - kubelet
          - kubeadm
          - kubectl

    - name: Source bash_completion
      become: true
      become_user: kubedev
      shell: source /usr/share/bash-completion/bash_completion
      args:
        executable: /bin/bash

    - name: Add kubectl bash completion
      become: true
      become_user: kubedev
      lineinfile:
        path: /home/kubedev/.bashrc
        line: source <(kubectl completion bash)
        state: present

    - name: Source .bashrc
      become: true
      become_user: kubedev
      shell: source /home/kubedev/.bashrc
      args:
        executable: /bin/bash

    - name: Restart kubelet
      service:
        name: kubelet
        daemon_reload: yes
        state: restarted

    - name: Copy kubeadm config
      become: true
      become_user: kubedev
      copy:
        src: ./setup/kubernetes/kubeadm-config.yaml
        dest: /tmp/kubeadm-config.yaml

    - name: Configure kubelet for digitalocean-cloud-controller-manager
      replace:
        path: /tmp/kubeadm-config.yaml
        regexp: "vProviderID"
        replace: "digitalocean://{{ droplet_id.stdout }}"

    # TODO: use ansibles lineinfile
    - name: Replace localAPIEndpoint.advertiseAddress with correct IP
      shell: sed -i "s/vAdvertiseAddress/{{ public_ip.stdout }}/g" /tmp/kubeadm-config.yaml

    - name: Replace apiServer.CertSANs with correct IP
      shell: sed -i "s/vCertSANs/{{ public_ip.stdout }}/g" /tmp/kubeadm-config.yaml

    - name: Replace apiServer.CertSANs with correct IP
      shell: cat /tmp/kubeadm-config.yaml

    - name: Initialize the Kubernetes cluster using kubeadm
      command: kubeadm init --config=/tmp/kubeadm-config.yaml

      # TODO: cleanup
    - name: Copy whole setup folder
      become: true
      become_user: kubedev
      copy:
        src: ./setup/
        dest: /home/kubedev/setup/

    - name: Setup kubeconfig for kubedev user
      command: "{{ item }}"
      with_items:
        - mkdir -p /home/kubedev/.kube
        - cp -i /etc/kubernetes/admin.conf /home/kubedev/.kube/config
        - chown kubedev:sudo -R /home/kubedev/.kube

    - name: Install Weave pod network
      become: true
      become_user: kubedev
      shell: kubectl apply -f https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')

    - name: Generate join command
      shell: kubeadm token create --print-join-command > /tmp/join-command

    - name: Copy join command to local file
      fetch:
        src: /tmp/join-command
        dest: join-command
        flat: true

    - name: Tainting master nodes
      become: true
      become_user: kubedev
      command: kubectl taint nodes --all node-role.kubernetes.io/master-

    # see: https://github.com/digitalocean/digitalocean-cloud-controller-manager/issues/361
    - name: Remove node label
      become: true
      become_user: kubedev
      command: kubectl label node master-0 node-role.kubernetes.io/master-

    - name: Clone digitalocean-cloud-controller-manager
      become: true
      become_user: kubedev
      ansible.builtin.git:
        repo: "https://github.com/digitalocean/digitalocean-cloud-controller-manager.git"
        dest: /tmp/digitalocean-cloud-controller-manager/

    - name: Create digitalocean-cloud-controller-manager secret
      become: true
      become_user: kubedev
      shell: echo "y" | /tmp/digitalocean-cloud-controller-manager/scripts/generate-secret.sh
      environment:
        DIGITALOCEAN_ACCESS_TOKEN: "{{ do_token }}"

    - name: Deploy digitalocean-cloud-controller-manager
      become: true
      become_user: kubedev
      shell: kubectl apply -f /tmp/digitalocean-cloud-controller-manager/releases/v0.1.32.yml

    - name: Deploy Ingress
      become: true
      become_user: kubedev
      shell: "{{ item }}"
      with_items:
        - kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.46.0/deploy/static/provider/do/deploy.yaml
        - kubectl create ns monitoring
        # TODO: wait for loadbalancer to be provisioned!
        - kubectl create -f /home/kubedev/setup/kubernetes/ingress.yaml

    - name: Install helm
      shell: "{{ item }}"
      with_items:
        - curl -fsSL -o /tmp/get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        - chmod 700 /tmp/get_helm.sh
        - /tmp/get_helm.sh

    - name: Add prometheus-community helm repo
      become: true
      become_user: kubedev
      community.kubernetes.helm_repository:
        name: prometheus-community
        repo_url: "https://prometheus-community.github.io/helm-charts"

    - name: Deploy kube-prometheus-stack inside monitoring namespace
      become: true
      become_user: kubedev
      community.kubernetes.helm:
        name: prometheus
        chart_ref: prometheus-community/kube-prometheus-stack
        update_repo_cache: yes
        release_namespace: monitoring
        create_namespace: true
        values:
          prometheus.prometheusSpec.podMonitorSelectorNilUsesHelmValues: false
          prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues: false

    - name: Set up NFS
      shell: "{{ item }}"
      with_items:
        - mkdir /var/nfs/general -p
        - chown nobody:nogroup /var/nfs/general
        - echo '/var/nfs/general    *(rw,sync,no_subtree_check,no_root_squash,no_all_squash,insecure)' | sudo tee -a /etc/exports
        - systemctl restart nfs-kernel-server

  handlers:
    - name: docker status
      service: name=docker state=started
