apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: priobike-ingress
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    {{- if .Values.production }}
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    {{ else }}
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    {{- end }}
spec:
  tls:
  - hosts:
    - grafana.{{ .Values.domain }}
    - prometheus.{{ .Values.domain }}
    - pushgateway.{{ .Values.domain }}
    - alertmanager.{{ .Values.domain }}
    secretName: priobike-tls
  rules:
    - host: grafana.{{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-grafana
                port:
                  number: 3000
    - host: prometheus.{{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-kube-prometheus-prometheus
                port:
                  number: 9090
    - host: pushgateway.{{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-pushgateway
                port:
                  number: 9091
    - host: alertmanager.{{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-kube-prometheus-alertmanager
                port:
                  number: 9093
