apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  {{- if .Values.production }}
  name: letsencrypt-prod
  {{ else }}
  name: letsencrypt-staging
  {{- end }}
  namespace: cert-manager
spec:
  acme:
    # The ACME server URL
    {{- if .Values.production }}
    server: https://acme-v02.api.letsencrypt.org/directory
    {{ else }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    {{- end }}
    # Email address used for ACME registration
    email: {{ .Values.acmeMail }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      {{- if .Values.production }}
      name: letsencrypt-prod
      {{ else }}
      name: letsencrypt-staging
      {{- end }}
    # Enable the HTTP-01 challenge provider
    solvers:
      - http01:
          ingress:
            class: nginx
