replicaCount: 1
resources:
  limits:
    cpu: 2000m
    memory: 1500Mi
  requests:
    cpu: 2000m
    memory: 1500Mi
emqxConfig:
  EMQX_PROMETHEUS__PUSH__GATEWAY__SERVER: http://prometheus-pushgateway.monitoring.svc:9091
  EMQX_PROMETHEUS__INTERVAL: 15000
  # EMQX_LOG__LEVEL: debug
emqxLoadedPlugins: >
  {emqx_management, true}.
  {emqx_recon, true}.
  {emqx_retainer, true}.
  {emqx_dashboard, true}.
  {emqx_telemetry, true}.
  {emqx_rule_engine, true}.
  {emqx_bridge_mqtt, false}.
  {emqx_prometheus, true}.
