additionalEnv:
  - name: DOCKER_VERNEMQ_ACCEPT_EULA
    value: "yes"
  - name: DOCKER_VERNEMQ_ALLOW_ANONYMOUS
    value: "on"
  - name: DOCKER_VERNEMQ_MAX_CLIENT_ID_SIZE
    value: "100"
  - name: DOCKER_VERNEMQ_MAX_ONLINE_MESSAGES
    value: "1000000"
  - name: DOCKER_VERNEMQ_MAX_OFFLINE_MESSAGES
    value: "100000"
  - name: DOCKER_VERNEMQ_MAX_INFLIGHT_MESSAGES
    value: "0"
  # - name: DOCKER_VERNEMQ_LEVELDB.maximum_memory.percent
  #   value: "40"
serviceMonitor:
  create: true
  labels:
    release: prometheus
envFrom: []
replicaCount: 1
resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 1000m
    memory: 1024Mi