---
- hosts: all
  become: true
  tasks:
    - name: Get Public IP
      shell: dig +short myip.opendns.com @resolver1.opendns.com
      register: public_ip

    - name: Get Droplet ID
      command: curl -s http://169.254.169.254/metadata/v1/id
      register: droplet_id

    - name: Create 'developers' group
      group:
        name: developers
        state: present

    - name: Allow 'developers' group to have passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: "^%developers"
        line: "%developers ALL=(ALL) NOPASSWD: ALL"
        validate: "visudo -cf %s"

    - name: Add the user 'kubedev'
      ansible.builtin.user:
        name: kubedev
        append: yes
        home: /home/kubedev/
        shell: /bin/bash
        groups: developers

    - name: Add SSH key to 'kubedev'
      authorized_key:
        user: kubedev
        state: present
        key: "{{ lookup('file', pub_key) }}"

    - name: Install packages that allow apt to be used over HTTPS
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common

    - name: Install additional necessary packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - mosquitto-clients
          - nfs-common
          - sshpass

    - name: Add an apt signing key for Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add apt repository for stable version
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present

    - name: Install docker and its dependecies
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - docker-ce
          - docker-ce-cli
          - containerd.io
      notify:
        - docker status

    - name: Add kubedev user to docker group
      user:
        name: kubedev
        group: docker

    - name: Remove swapfile from /etc/fstab
      mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      with_items:
        - swap
        - none

    - name: Disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: Add an apt signing key for Kubernetes
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Adding apt repository for Kubernetes
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes.list

    - name: Install Kubernetes binaries
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - kubelet
          - kubeadm
          - kubectl

    - name: Configure kubelet for digitalocean-cloud-controller-manager
      lineinfile:
        path: /etc/default/kubelet
        line: KUBELET_EXTRA_ARGS=--cloud-provider=external --provider-id=digitalocean://{{ droplet_id.stdout }}
        create: yes

    - name: Restart kubelet
      service:
        name: kubelet
        daemon_reload: yes
        state: restarted

    - name: Copy the join command to remote location
      copy: src=join-command dest=/tmp/join-command.sh mode=0777

    - name: Join the node to cluster
      become: true
      command: sh /tmp/join-command.sh

  handlers:
    - name: docker status
      service: name=docker state=started
