# connect with: kubectl exec --stdin --tty load-it -- /bin/ash
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: load-it
  name: load-it
  namespace: default
spec:
  containers:
    - image: ghcr.io/niclaszll/load-it:1.0.0
      name: load-it
      command: ["sleep", "infinity"]
  tolerations:
    - key: "kind"
      operator: "Equal"
      value: "testing"
      effect: "NoSchedule"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
