{
 "title": "MQTT Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "MQTT Publish Sent and Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(mqtt_publish_sent[5m])" },
    {
     "expr": "rate(mqtt_publish_received[5m])"
    }
   ]
  },
  {
   "title": "VerneMQ Replicas",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_statefulset_replicas{statefulset=\"vernemq\"}"
    }
   ]
  },
  {
   "title": "MQTT Connect Received",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mqtt_connect_received" }
   ]
  },
  {
   "title": "MQTT Published Failed Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mqtt_publish_error" }
   ]
  }
 ]
}