apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: vAdvertiseAddress
  bindPort: 6443
nodeRegistration:
  kubeletExtraArgs:
    cloud-provider: "external"
    provider-id: "vProviderID"
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
clusterName: cloud-dev
networking:
  podSubnet: "10.244.0.0/16"
apiServer:
  extraArgs:
    kubelet-preferred-address-types: "InternalIP,ExternalIP,Hostname"
  CertSANs:
    - "vCertSANs"
controllerManager:
  extraArgs:
    "bind-address": "0.0.0.0"
    "port": "10252"
scheduler:
  extraArgs:
    "bind-address": "0.0.0.0"
    "port": "10251"
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
metricsBindAddress: "0.0.0.0:10249"