---
- hosts: all
  tasks:
    - name: Update hosts entry with correct IP
      become: true
      shell: sed 's/127\.0\.2\.1/192\.168\.99\.100/g' -i /etc/hosts

    - name: Install packages that allow apt to be used over HTTPS
      become: true
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common

    - name: Install additional necessary packages
      become: true
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - bash-completion
          - mosquitto-clients
          - nfs-kernel-server

    - name: Add an apt signing key for Docker
      become: true
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add apt repository for stable version
      become: true
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present

    - name: Install docker and its dependecies
      become: true
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - docker-ce
          - docker-ce-cli
          - containerd.io
      notify:
        - docker status

    - name: Add vagrant user to docker group
      become: true
      user:
        name: vagrant
        group: docker

    - name: Remove swapfile from /etc/fstab
      become: true
      mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      with_items:
        - swap
        - none

    - name: Disable swap
      become: true
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: Add an apt signing key for Kubernetes
      become: true
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Adding apt repository for Kubernetes
      become: true
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes.list

    - name: Install Kubernetes binaries
      become: true
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - kubelet
          - kubeadm
          - kubectl

    - name: Source bash_completion
      shell: source /usr/share/bash-completion/bash_completion
      args:
        executable: /bin/bash

    - name: Add kubectl bash completion
      lineinfile:
        path: /home/vagrant/.bashrc
        line: source <(kubectl completion bash)
        state: present

    - name: Source .bashrc
      shell: source /home/vagrant/.bashrc
      args:
        executable: /bin/bash

    - name: Restart kubelet
      become: true
      service:
        name: kubelet
        daemon_reload: yes
        state: restarted

    - name: Copy kubeadm config
      copy:
        src: ./kubernetes/kubeadm-config.yaml
        dest: /tmp/kubeadm-config.yaml

    - name: Initialize the Kubernetes cluster using kubeadm
      become: true
      command: kubeadm init --config=/tmp/kubeadm-config.yaml

    - name: Setup kubeconfig for vagrant user
      become: true
      command: "{{ item }}"
      with_items:
        - mkdir -p /home/vagrant/.kube
        - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
        - chown vagrant:vagrant -R /home/vagrant/.kube

    - name: Install Weave pod network
      shell: kubectl apply -f https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')

    - name: Generate join command
      command: kubeadm token create --print-join-command
      register: join_command

    - name: Copy join command to local file
      local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"

    - name: Tainting master nodes
      command: kubectl taint nodes --all node-role.kubernetes.io/master-

    - name: Install helm
      shell: curl -s https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

    - name: Add prometheus-community helm repo
      community.kubernetes.helm_repository:
        name: prometheus-community
        repo_url: "https://prometheus-community.github.io/helm-charts"

    - name: Deploy kube-prometheus-stack inside monitoring namespace
      community.kubernetes.helm:
        name: prometheus
        chart_ref: prometheus-community/kube-prometheus-stack
        update_repo_cache: yes
        release_namespace: monitoring
        create_namespace: true
        values:
          prometheus.prometheusSpec.podMonitorSelectorNilUsesHelmValues: false
          prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues: false
    
    - name: Deploy MetalLB
      shell: "{{ item }}"
      with_items:
        - kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.6/manifests/namespace.yaml
        - kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.6/manifests/metallb.yaml
        - kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"
        - kubectl create -f /home/vagrant/setup/kubernetes/metallb-config.yaml
    
    - name: Add ingress-nginx helm repo
      community.kubernetes.helm_repository:
        name: ingress-nginx
        repo_url: "https://kubernetes.github.io/ingress-nginx"

    - name: Deploy ingress-nginx
      community.kubernetes.helm:
        name: my-ingress-nginx
        chart_ref: ingress-nginx/ingress-nginx
        update_repo_cache: yes
        release_namespace: ingress-nginx
        create_namespace: true
        values:
          hostNetwork: true
          hostPort.enabled: true
          kind: DaemonSet
    
    # fix for "failed calling webhook" error
    # see: https://stackoverflow.com/a/63021823
    - name: Delete ValidatingWebhookConfiguration for ingress-nginx
      command: kubectl delete -A ValidatingWebhookConfiguration my-ingress-nginx-admission -n ingress-nginx

    - name: Deploy Ingress
      command: kubectl create -f /home/vagrant/setup/kubernetes/ingress.yaml

    - name: Set up NFS
      become: true
      shell: "{{ item }}"
      with_items:
        - mkdir /var/nfs/general -p
        - chown nobody:nogroup /var/nfs/general
        - echo '/var/nfs/general    *(rw,sync,no_subtree_check,no_root_squash,no_all_squash,insecure)' | sudo tee -a /etc/exports
        - systemctl restart nfs-kernel-server

  handlers:
    - name: docker status
      service: name=docker state=started
