---
- hosts: all
  tasks:
    - name: Install nfs-subdir-external-provisioner repo
      community.kubernetes.helm_repository:
        name: nfs-subdir-external-provisioner
        repo_url: "https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner"

    - name: Deploy nfs-subdir-external-provisioner
      community.kubernetes.helm:
        name: nfs-subdir-external-provisioner
        chart_ref: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
        update_repo_cache: yes
        values:
          nfs.server: 192.168.99.100
          nfs.path: /var/nfs/general
          storageClass.defaultClass: true

    - name: Clone mongo-kubernetes-operator
      ansible.builtin.git:
        repo: https://github.com/mongodb/mongodb-kubernetes-operator.git
        dest: /tmp/mongo-operator

    - name: Deploy mongo-kubernetes-operator
      shell: "{{ item }}"
      with_items:
        - kubectl apply -f /tmp/mongo-operator/config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml
          # Install necessary roles and role-bindings
        - kubectl create ns mongo
        - kubectl apply -k /tmp/mongo-operator/config/rbac/ -n mongo
          # Install Operator
        - kubectl create -f /tmp/mongo-operator/config/manager/manager.yaml -n mongo

    - name: Deploy MongoDB
      shell: kubectl create -f /home/vagrant/setup/kubernetes/mongo-config.yaml -n mongo

    - name: Install VerneMQ repo
      community.kubernetes.helm_repository:
        name: vernemq
        repo_url: "https://vernemq.github.io/docker-vernemq"

    - name: Deploy VerneMQ
      community.kubernetes.helm:
        name: vernemq
        chart_ref: vernemq/vernemq
        update_repo_cache: yes
        release_namespace: mqtt
        create_namespace: true
        values_files:
          - /home/vagrant/setup/kubernetes/vernemq-helm-values.yaml
