---
- hosts: localhost
  connection: local
  tasks:
    - name: Add ingress-nginx repo
      community.kubernetes.helm_repository:
        name: ingress-nginx
        repo_url: "https://kubernetes.github.io/ingress-nginx"

    - name: Install ingress-nginx
      community.kubernetes.helm:
        name: nginx-ingress
        chart_ref: ingress-nginx/ingress-nginx
        update_repo_cache: yes
        release_namespace: ingress-nginx
        create_namespace: true
        values:
          controller.publishService.enabled: true

    - name: Wait for loadbalancer to be provisioned
      shell: kubectl -n ingress-nginx get svc nginx-ingress-ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
      register: lb_result
      until: lb_result.stdout | length > 0
      # max wait time 7m30s
      retries: 30
      delay: 15

    - name: Create monitoring namespace
      community.kubernetes.k8s:
        name: monitoring
        api_version: v1
        kind: Namespace
        state: present

    - name: Deploy setup-ingress chart from local path
      community.kubernetes.helm:
        name: setup-ingress
        chart_ref: ../setup/helm/charts/setup-ingress
        release_namespace: monitoring
        values:
          domain: "{{ domain }}"
          production: "{{ production }}"

    # unfortunately using community.kubernetes.helm doesn't work correctly ("no token found"), use shell instead
    - name: Add ExternalDNS Repo
      shell: helm repo add bitnami https://charts.bitnami.com/bitnami

    - name: Update helm (not working via update_repo_cache)
      shell: helm repo update

    - name: Deploy ExternalDNS to automatically Manage DNS Records
      shell: helm install external-dns bitnami/external-dns --set provider=digitalocean,digitalocean.apiToken="{{ do_token }}",interval="1m",policy=sync -n kube-system

    - name: Add cert-manager helm repo
      community.kubernetes.helm_repository:
        name: jetstack
        repo_url: "https://charts.jetstack.io"

    - name: Deploy cert-manager
      community.kubernetes.helm:
        name: cert-manager
        chart_ref: jetstack/cert-manager
        chart_version: v1.3.1
        update_repo_cache: yes
        release_namespace: cert-manager
        create_namespace: true
        wait: yes
        values:
          installCRDs: true

    - name: Wait for cert-manager to be fully provisioned
      shell: kubectl get pods --namespace cert-manager -o json
      register: cert_manager_result
      until: cert_manager_result.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
      # max wait time 2m
      retries: 12
      delay: 10

    - name: Deploy setup-issuer chart from local path
      community.kubernetes.helm:
        name: setup-issuer
        chart_ref: ../setup/helm/charts/setup-issuer
        release_namespace: cert-manager
        values:
          acmeMail: "{{ acme_mail }}"
          production: "{{ production }}"

    - name: Add prometheus-community helm repo
      community.kubernetes.helm_repository:
        name: prometheus-community
        repo_url: "https://prometheus-community.github.io/helm-charts"

    - name: Deploy kube-prometheus-stack
      community.kubernetes.helm:
        name: prometheus
        chart_ref: prometheus-community/kube-prometheus-stack
        update_repo_cache: yes
        release_namespace: monitoring
        create_namespace: true
        # 16.6.4 breaks kube-state-metrics monitoring, wait till fix
        chart_version: 16.6.3
        values:
          prometheus.prometheusSpec.podMonitorSelectorNilUsesHelmValues: false
          prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues: false

    - name: Deploy prometheus-adapter
      community.kubernetes.helm:
        name: prometheus-adapter
        chart_ref: prometheus-community/prometheus-adapter
        update_repo_cache: yes
        release_namespace: monitoring
        values_files:
          - ../setup/helm/values/prometheus-adapter-values.yaml

    - name: Install mongo-kubernetes-operator CRDs
      shell: kubectl apply -f https://raw.githubusercontent.com/mongodb/mongodb-kubernetes-operator/master/config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml

    - name: Create mongo namespace
      community.kubernetes.k8s:
        name: mongo
        api_version: v1
        kind: Namespace
        state: present
    
    - name: Deploy mongo-kubernetes-operator
      shell: "{{ item }}"
      with_items:
        # Install necessary roles and role-bindings
        - kubectl apply -f https://raw.githubusercontent.com/mongodb/mongodb-kubernetes-operator/master/config/rbac/role.yaml -n mongo
        - kubectl apply -f https://raw.githubusercontent.com/mongodb/mongodb-kubernetes-operator/master/config/rbac/role_binding.yaml -n mongo
        - kubectl apply -f https://raw.githubusercontent.com/mongodb/mongodb-kubernetes-operator/master/config/rbac/service_account.yaml -n mongo
        # Install Operator
        - kubectl apply -f https://raw.githubusercontent.com/mongodb/mongodb-kubernetes-operator/master/config/manager/manager.yaml -n mongo

    - name: Deploy MongoDB
      community.kubernetes.k8s:
        state: present
        namespace: mongo
        src: ../setup/kubernetes/mongo-config.yaml

    # - name: Install VerneMQ repo
    #   community.kubernetes.helm_repository:
    #     name: vernemq
    #     repo_url: "https://vernemq.github.io/docker-vernemq"

    # - name: Deploy VerneMQ
    #   community.kubernetes.helm:
    #     name: vernemq
    #     chart_ref: vernemq/vernemq
    #     update_repo_cache: yes
    #     release_namespace: mqtt
    #     create_namespace: true
    #     values_files:
    #       - ../setup/helm/values/vernemq-helm-values.yaml

    # use cloned repo for now, helm chart not updated yet
    - name: Deploy VerneMQ from local path
      community.kubernetes.helm:
        name: vernemq
        chart_ref: ../setup/helm/charts/vernemq
        release_namespace: mqtt
        create_namespace: true
        values_files:
          - ../setup/helm/values/vernemq-helm-values.yaml
