apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: mzbench
  name: mzbench
  namespace: testing
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mzbench
  template:
    metadata:
      labels:
        run: mzbench
    spec:
      containers:
        - name: mzbench
          image: zellerhub/mzbench:1.0.1
          ports:
            - containerPort: 4800
          resources:
            requests:
              memory: "5Gi"
              cpu: "3400m"
            limits:
              memory: "5Gi"
              cpu: "3400m"
      tolerations:
        - key: "kind"
          operator: "Equal"
          value: "testing"
          effect: "NoSchedule"
